services:
  jobapplication.api:
    image: ${DOCKER_REGISTRY-}jobapplicationapi
    build:
      context: .
      dockerfile: src/JobApplication.API/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql-db,1433;Database=JobApplicationsDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;"
    depends_on:
      - mssql-db

  resume.api:
    image: ${DOCKER_REGISTRY-}resumeapi
    build:
      context: .
      dockerfile: src/Resume.API/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql-db,1433;Database=ResumeDb;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;"
    ports:
      - "5001:8080"
    env_file:
      - .env
    depends_on:
      - mssql-db

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

